name: build and test

on:
  - push
  - pull_request

jobs:
  lint:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup go
        uses: https://github.com/actions/setup-go@v4
        with:
          go-version: '>=1.20.1'
      - name: Build
        env:
          GOPROXY: https://goproxy.io,direct
        run: |
          cd khulnasoft-vet
          make build
          make lint
          make vet
